<?xml version="1.0" encoding="UTF-8"?>
<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>CaetanoSoft</groupId>
	<artifactId>JavaDemoApp</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>21</maven.compiler.release>
		<exec.mainClass>CaetanoSoft.JavaDemoApp.JavaDemoApp</exec.mainClass>
	</properties>
	<name>Java Demo App</name>
	<description>Basic Java Swing application to show all UI functionality.
Supports splash screen and translation to portuguese.
Can be used as a base to a new Java GUI application.</description>
	<build>
    <resources>
      <resource>
				<filtering>true</filtering>
				<directory>src/main/java</directory>
				<includes>
					<include>**/LICENSE</include>
				</includes>
      </resource>
      <resource>
        <targetPath>CaetanoSoft/JavaDemoApp/Resources</targetPath>
        <filtering>true</filtering>
        <directory>src/main/java/CaetanoSoft/JavaDemoApp/Resources</directory>
        <includes>
          <include>**/*.gif</include>
          <include>**/*.png</include>
          <include>**/*.ico</include>
          <include>**/*.bmp</include>
          <include>**/*.jpg</include>
        </includes>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.1</version>
				<configuration>
					<archive>
						<index>true</index>
						<addMavenDescriptor>false</addMavenDescriptor>
						<manifestFile>src/main/java/META-INF/MANIFEST.MF</manifestFile>
						<manifest>
							<addClasspath>true</addClasspath>
							<classpathPrefix>lib/</classpathPrefix>
							<mainClass>CaetanoSoft.JavaDemoApp.JavaDemoApp</mainClass>
						</manifest>
						<manifestEntries>
							<Built-By></Built-By>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.15.0</version>
				<configuration>
					<compilerArgs>
						<arg>-Xlint</arg>
					</compilerArgs>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>Library</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.mysql</groupId>
			<artifactId>mysql-connector-j</artifactId>
			<version>9.7.0</version>
      <scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>13.4.0.jre11</version>
      <scope>runtime</scope>
		</dependency>
	</dependencies>
</project>
