# Swing properties

# Microsoft Windows Look & Feel (Only on Windows OS, since JRE v1.2)
swing.defaultlaf=com.sun.java.swing.plaf.windows.WindowsLookAndFeel
# Microsoft Windows Classic Look & Feel (Only on Windows OS, since JRE v1.1)
#swing.defaultlaf=com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel
# Apple Macintosh Look & Feel(Only on Mac OS, since JRE v1.1)
#swing.defaultlaf=com.sun.java.swing.plaf.mac.MacLookAndFeel
# CDE/Motif Look & Feel (All Java platforms, since JRE v1.1)
#swing.defaultlaf=com.sun.java.swing.plaf.motif.MotifLookAndFeel
# GTK+ Look & Feel (Only on OS with GTK 2.2 GUI installed, since JRE v1.2)
#swing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
# Nimbus Look & Feel (All Java platforms, since JRE v1.6)#swing.defaultlaf=com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel
# Java/Metal Look & Feel (All Java platforms, since JRE v1.1)
#swing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
