# Swing properties

#* Microsoft Windows Look & Feel (Only on Windows XP OS or later, since JRE v1.2)
#swing.defaultlaf=com.sun.java.swing.plaf.windows.WindowsLookAndFeel
#* Microsoft Windows Classic Look & Feel (Only on Windows OS, since JRE v1.1)
#swing.defaultlaf=com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel
#* Apple OS X Look & Feel (Only on macOS X, since JRE v1.6)
#swing.defaultlaf=com.apple.laf.AquaLookAndFeel
#* Apple Classic Look & Feel (Only on Mac OS 9 or earlier, since JRE v1.1)
#swing.defaultlaf=com.sun.java.swing.plaf.mac.MacLookAndFeel
#* GTK+ Look & Feel (Only on Linux/UNIX OS with GTK 2.2 GUI installed, since JRE v1.4.2)
#swing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
#swing.gtkthemefile=PATH_2_PROPERTIES_FILE/gtkrc
#* CDE/Motif Look & Feel (All Java platforms, since JRE v1.1)
#swing.defaultlaf=com.sun.java.swing.plaf.motif.MotifLookAndFeel
#* Metal Look & Feel (All Java platforms, since JRE v1.1)
#swing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel
#* Nimbus Look & Feel (All Java platforms, since JRE v1.6)
swing.defaultlaf=com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel

