# Edit as UTF-8

# Debugging Level: 0 => Off; 1 => Only Errors (default); 2 => Only Errors and Warnings; 4 => Only Errors, Warnings and Information; -1 => All
DEBUG_LEVEL=4
# Time, in seconds, for each thread sleeep  (default is 1)
THREAD_SLEEP_TIME=1
# DBMS Driver class  (mandatory)
JDBC_DRIVER=com.mysql.cj.jdbc.Driver
# Conection URL for DB  (mandatory)
JDBC_URL=jdbc:mysql://localhost:3306/BricksCollector?connectTimeout=5000
# Conection Timeout (in milliseconds) for DB  (default is 5000)
JDBC_CONNECT_TIMEOUT=5000
# DB login username
JDBC_USERNAME=BricksCollector_User
# DB login password
JDBC_PASSWORD=SecretPassword2!

